# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='specialty',
        ),
    ]
