# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20161207_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='practice_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.PracticeType'),
        ),
    ]
