# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20161207_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='practice_type',
            new_name='practices',
        ),
    ]
