# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20161207_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='practices',
            field=models.ManyToManyField(blank=True, to='users.PracticeType'),
        ),
    ]
