# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20161212_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apply_survey',
            field=models.BooleanField(default=True),
        ),
    ]
