# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-21 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_apply_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_survey_agree',
            field=models.BooleanField(default=False),
        ),
    ]
