# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 13:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholAbuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AntiCoagulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ASAAllergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HTN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HXofBleeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HXofMalignancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NonCardiaticSurgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('middle_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_procedure', models.DateField()),
                ('ballons', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('warfarin_intolerance', models.BooleanField(default=False)),
                ('inr_inestability', models.BooleanField(default=False)),
                ('noac_allergy_or_intolerance', models.BooleanField(default=False)),
                ('hb', models.FloatField(blank=True, null=True)),
                ('plts', models.FloatField(blank=True, null=True)),
                ('inr', models.FloatField(blank=True, null=True)),
                ('creat', models.FloatField(blank=True, null=True)),
                ('egfr', models.FloatField(blank=True, null=True)),
                ('ast', models.FloatField(blank=True, null=True)),
                ('alt', models.FloatField(blank=True, null=True)),
                ('alp', models.FloatField(blank=True, null=True)),
                ('bilirubin', models.FloatField(blank=True, null=True)),
                ('troponin', models.FloatField(blank=True, null=True)),
                ('chf', models.BooleanField(default=False)),
                ('diabetes_mellitus', models.BooleanField(default=False)),
                ('stroke', models.BooleanField(default=False)),
                ('tia', models.BooleanField(default=False)),
                ('renal_dysfunction', models.BooleanField(default=False)),
                ('ckd_on_dialysis', models.BooleanField(default=False)),
                ('renal_transplant', models.BooleanField(default=False)),
                ('liver_dysfunction', models.BooleanField(default=False)),
                ('drugs_abuse', models.BooleanField(default=False)),
                ('chronic_nsaids_rx', models.BooleanField(default=False)),
                ('excesive_fall_risk', models.BooleanField(default=False)),
                ('alcohol_abuse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.AlcoholAbuse')),
                ('asa_allergy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.ASAAllergy')),
                ('htn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.HTN')),
                ('hx_of_bleeding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.HXofBleeding')),
                ('hx_of_malignancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.HXofMalignancy')),
                ('indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.Indication')),
                ('prev_anti_coagulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.AntiCoagulation')),
            ],
        ),
        migrations.CreateModel(
            name='Stent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VascularDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VesselsPCI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='stent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.Stent'),
        ),
        migrations.AddField(
            model_name='patient',
            name='type_af',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.TypeAF'),
        ),
        migrations.AddField(
            model_name='patient',
            name='upcoming_non_cardiatic_surgery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.NonCardiaticSurgery'),
        ),
        migrations.AddField(
            model_name='patient',
            name='vascular_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.VascularDisease'),
        ),
        migrations.AddField(
            model_name='patient',
            name='vessels_pci',
            field=models.ManyToManyField(to='data_entry.VesselsPCI'),
        ),
    ]
