# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 13:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='ballons',
        ),
        migrations.AddField(
            model_name='patient',
            name='alp_um',
            field=models.CharField(choices=[('um1', 'um1'), ('um2', 'um2')], default='um1', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='alt_um',
            field=models.CharField(choices=[('um1', 'um1'), ('um2', 'um2')], default='um1', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='ast_um',
            field=models.CharField(choices=[('um1', 'um1'), ('um2', 'um2')], default='um1', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='balloons',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='patient',
            name='bilirubin_um',
            field=models.CharField(choices=[('um1', 'um1'), ('um2', 'um2')], default='um1', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='creat_um',
            field=models.CharField(choices=[('um1', 'um1'), ('um2', 'um2')], default='um1', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='egfr_um',
            field=models.CharField(choices=[('um1', 'um1'), ('um2', 'um2')], default='um1', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='followed_recommendation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hb_um',
            field=models.CharField(choices=[('um1', 'um1'), ('um2', 'um2')], default='um1', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='inr_um',
            field=models.CharField(choices=[('um1', 'um1'), ('um2', 'um2')], default='um1', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='plts_um',
            field=models.CharField(choices=[('um1', 'um1'), ('um2', 'um2')], default='um1', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='reason_not_followed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='troponin_um',
            field=models.CharField(choices=[('um1', 'um1'), ('um2', 'um2')], default='um1', max_length=20),
        ),
    ]
