# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_auto_20160902_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='drugs_abuse',
            new_name='drug_abuse',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='excesive_fall_risk',
            new_name='excessive_fall_risk',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='inr_inestability',
            new_name='inr_instability',
        ),
    ]
