# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0004_auto_20160906_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='identification',
            field=models.CharField(max_length=50),
        ),
    ]
