# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0006_remove_patient_vascular_disease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VascularDisease',
        ),
        migrations.AddField(
            model_name='patient',
            name='vascular_disease',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Aortic'), (2, 'Coronary'), (3, 'Peripheral')], default=0),
        ),
    ]
