# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0007_auto_20160912_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='stent',
        ),
        migrations.DeleteModel(
            name='Stent',
        ),
    ]
