# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0009_patient_stent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='type_af',
        ),
        migrations.DeleteModel(
            name='TypeAF',
        ),
    ]
