# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0012_auto_20160913_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='indication',
            field=models.CharField(choices=[('STEMI', 'STEMI'), ('NSTEMI', 'NSTEMI'), ('UA', 'UA'), ('SCAD', 'SCAD')], default='UA', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='af_type',
            field=models.IntegerField(choices=[(0, 'No Atrial Fibrilation'), (1, 'Paroxysmal'), (2, 'Persistent'), (3, 'Permanent')], default=0),
        ),
    ]
