# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0013_auto_20160913_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='asa_allergy',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hx_of_bleeding',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hx_of_malignancy',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prev_anti_coagulation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='upcoming_non_cardiatic_surgery',
        ),
        migrations.AlterField(
            model_name='patient',
            name='htn',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes, Controlled HTN on meds'), (2, 'Yes, Uncontrolled HTN on meds SBP > 160 mmHg')], default=0),
        ),
        migrations.DeleteModel(
            name='AntiCoagulation',
        ),
        migrations.DeleteModel(
            name='ASAAllergy',
        ),
        migrations.DeleteModel(
            name='HXofBleeding',
        ),
        migrations.DeleteModel(
            name='HXofMalignancy',
        ),
        migrations.DeleteModel(
            name='NonCardiaticSurgery',
        ),
    ]
