# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0014_auto_20160913_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='asa_allergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='hx_of_bleeding',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'GI'), (2, 'ICH')], default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='hx_of_malignancy',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes, prior'), (2, 'Yes, currently under treatment')], default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='prev_anti_coagulation',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Warfarin'), (2, 'Ribaroxaban'), (3, 'Dabigatran'), (4, 'Apixiban')], default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='upcoming_non_cardiatic_surgery',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes, < 6 months'), (2, 'Yes, >= 6 months')], default=0),
        ),
    ]
