# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0015_auto_20160913_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='alp',
            new_name='ggt',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='alp_um',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='inr_um',
        ),
        migrations.AddField(
            model_name='patient',
            name='ggt_um',
            field=models.CharField(choices=[('U/L', 'U/L')], default='um1', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='alt_um',
            field=models.CharField(choices=[('U/L', 'U/L')], default='um1', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ast_um',
            field=models.CharField(choices=[('U/L', 'U/L')], default='um1', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bilirubin_um',
            field=models.CharField(choices=[('micromol/L', 'micromol/L'), ('mg/dL', 'mg/dL')], default='um1', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='creat_um',
            field=models.CharField(choices=[('micromol/L', 'micromol/L'), ('mg/dL', 'mg/dL')], default='um1', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='egfr_um',
            field=models.CharField(choices=[('mL/min/1.73m2', 'mL/min/1.73m2')], default='um1', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hb_um',
            field=models.CharField(choices=[('g/L', 'g/L'), ('g/dL', 'g/dL')], default='um1', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='plts_um',
            field=models.CharField(choices=[('10^9xL', '10^9xL'), ('mm3', 'mm3'), ('mL', 'mL')], default='um1', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='troponin_um',
            field=models.CharField(choices=[('ng/mL', 'ng/mL')], default='um1', max_length=20),
        ),
    ]
