# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0018_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='balloons',
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_procedure',
            field=models.DateField(blank=True, null=True),
        ),
    ]
