# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0019_auto_20160923_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='stent',
        ),
        migrations.AddField(
            model_name='patient',
            name='bms_stent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='des_stent',
            field=models.BooleanField(default=False),
        ),
    ]
