# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0020_auto_20160923_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='af_type',
            field=models.IntegerField(choices=[(1, 'Paroxysmal'), (2, 'Persistent'), (3, 'Permanent')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hx_of_bleeding',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Gastrointestinal'), (2, 'Intracerebral hemorrhage')], default=0),
        ),
    ]
