# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0021_auto_20160923_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='patient',
            name='vessels_pci',
            field=models.ManyToManyField(blank=True, to='data_entry.VesselsPCI'),
        ),
    ]
