# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 16:29
from __future__ import unicode_literals

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Patient = apps.get_model('data_entry', 'Patient')
    for patient in Patient.objects.all():
        patient.key = uuid.uuid4()
        patient.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0023_patient_key'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
