# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0024_auto_20161004_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
