# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 15:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0027_remove_patient_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
