# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0028_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_of_procedure',
        ),
    ]
