# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0030_auto_20161205_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='alt_um',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ast',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ast_um',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bilirubin',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bilirubin_um',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='creat',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='creat_um',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='egfr',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='egfr_um',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ggt',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ggt_um',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hb',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hb_um',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='inr',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='plts',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='plts_um',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='troponin',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='troponin_um',
        ),
    ]
