# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0031_auto_20161205_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='chronic_nsaids_rx',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ckd_on_dialysis',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='excessive_fall_risk',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hx_of_malignancy',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='renal_transplant',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='upcoming_non_cardiatic_surgery',
        ),
    ]
