# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0032_auto_20161205_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prev_anti_coagulation',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Warfarin'), (2, 'Ribaroxaban'), (3, 'Dabigatran'), (4, 'Apixiban')], default=0, null=True),
        ),
    ]
