# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0033_auto_20161207_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='vessels_pci',
        ),
        migrations.DeleteModel(
            name='VesselsPCI',
        ),
    ]
