# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0035_auto_20161213_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ccs_therapy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mcm_therapy',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='indication',
            field=models.CharField(choices=[('STEMI', 'STEMI'), ('NSTEMI', 'NSTEMI'), ('UA', 'UA'), ('SCAD', 'Stable CAD')], max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prev_anti_coagulation',
            field=models.IntegerField(blank=True, choices=[(1, 'Warfarin'), (2, 'Ribaroxaban'), (3, 'Dabigatran'), (4, 'Apixiban')], default=0, null=True),
        ),
    ]
