# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0036_auto_20170121_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prev_anti_coagulation',
            field=models.IntegerField(blank=True, choices=[(1, 'Warfarin'), (2, 'Rivaroxaban'), (3, 'Dabigatran'), (4, 'Apixiban')], default=0, null=True),
        ),
    ]
