# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0037_auto_20170224_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='chosen_therapy',
            field=models.CharField(choices=[('mcm', 'Hamilton AF-PCI'), ('ccs', 'CCS'), ('other', 'Other')], max_length=10),
        ),
    ]
