# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0038_auto_20170306_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pci_risk_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='pci_risk_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='pci_risk_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='pci_risk_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='pci_risk_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='pci_risk_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='pci_risk_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='pci_risk_8',
            field=models.BooleanField(default=False),
        ),
    ]
