# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 19:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0040_patient_hemoglobin_mgdl'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
