# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0041_patient_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='creatinine_mgdL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='creatinine_umolL',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
