# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0045_patient_pci_risk_9'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='deb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='drug_coated_stent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='poba',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='htn',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes, Controlled on meds'), (2, 'Yes, Uncontrolled on meds SBP > 160 mmHg')], default=0),
        ),
    ]
