# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0046_auto_20170704_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='noac_allergy_or_intolerance',
            new_name='doac_allergy_or_intolerance',
        ),
    ]
