# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0047_auto_20170704_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='drug_abuse',
        ),
        migrations.AlterField(
            model_name='patient',
            name='vascular_disease',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Peripheral vascular disease'), (2, 'Myocardial infarction'), (3, 'Aortic plaque')], default=0),
        ),
    ]
