# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0048_auto_20170705_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tia_stroke_or_sysemb',
            field=models.BooleanField(default=False),
        ),
    ]
