# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 22:25
from __future__ import unicode_literals

from django.db import migrations

def set_new_data(apps, schema_editor):
	Patient = apps.get_model('data_entry','Patient')

	for p in Patient.objects.all():
		#stroke, tia, tia_stroke_or_sysemb
		p.tia_stroke_or_sysemb = p.stroke or p.tia
		p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0049_patient_tia_stroke_or_sysemb'),
    ]

    operations = [
    	migrations.RunPython(set_new_data)
    ]
