# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0050_auto_20170705_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='stroke',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='tia',
        ),
    ]
