# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0051_auto_20170705_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='drug_abuse',
            field=models.BooleanField(default=False),
        ),
    ]
