# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0052_patient_drug_abuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='aim',
            field=models.BooleanField(default=False),
        ),
    ]
