# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0053_patient_aim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='hemoglobin_gL',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hemoglobin_mgdL',
        ),
    ]
