# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-06 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0055_auto_20170805_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='ccs_therapy',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='chosen_therapy',
        ),
        migrations.AddField(
            model_name='patient',
            name='agree_therapy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='htn',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes, Controlled on medicaments'), (2, 'Yes, Uncontrolled on medicaments SBP > 160 mmHg')], default=0),
        ),
    ]
