# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0056_auto_20180306_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bvs',
            field=models.BooleanField(default=False),
        ),
    ]
