# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0058_auto_20180314_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='high_risk_af_8',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='high_risk_af_9',
        ),
    ]
