# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0059_auto_20180314_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='frailty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='prior_acute_cs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='prior_stent_thrombosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking_history',
            field=models.IntegerField(choices=[(0, 'Never smoker'), (1, 'Former smoker'), (2, 'Current smoker')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hx_of_bleeding',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Gastrointestinal'), (2, 'Intracerebral hemorrhage'), (3, 'Hospitalization for bleeding within last year')], default=0),
        ),
    ]
