# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-19 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0061_auto_20180315_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='mcm_therapy',
            new_name='ccs_therapy',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='indication',
            new_name='elective_pci',
        ),
    ]
