# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-16 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0062_auto_20180319_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diabetes_mellitus',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
