# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 15:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Creation Date and Time')),
                ('modified', models.DateField(editable=False, null=True, verbose_name='Modification Date and Time')),
                ('publish', models.BooleanField(default=True, help_text='Este campo activará el contenido en la pagina.', verbose_name='Publicar')),
                ('order', models.IntegerField(blank=True, default=0, help_text='Este campo será utilizado para definir el orden del contenido. ', verbose_name='Orden')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckboxChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('id_in_question', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('id_in_question', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Creation Date and Time')),
                ('modified', models.DateField(editable=False, null=True, verbose_name='Modification Date and Time')),
                ('publish', models.BooleanField(default=True, help_text='Este campo activará el contenido en la pagina.', verbose_name='Publicar')),
                ('order', models.IntegerField(blank=True, default=0, help_text='Este campo será utilizado para definir el orden del contenido. ', verbose_name='Orden')),
                ('id_in_survey', models.IntegerField()),
                ('type', models.CharField(choices=[('multiplechoice', 'MultipleChoiceQuestion'), ('checkbox', 'CheckboxQuestion'), ('paragraph', 'ParagraphQuestion'), ('numeric', 'NumericQuestion'), ('text', 'TextQuestion')], max_length=25)),
                ('title', models.CharField(max_length=500)),
                ('help_text', models.CharField(max_length=500, null=True)),
                ('is_required', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id_in_survey'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Creation Date and Time')),
                ('modified', models.DateField(editable=False, null=True, verbose_name='Modification Date and Time')),
                ('publish', models.BooleanField(default=True, help_text='Este campo activará el contenido en la pagina.', verbose_name='Publicar')),
                ('order', models.IntegerField(blank=True, default=0, help_text='Este campo será utilizado para definir el orden del contenido. ', verbose_name='Orden')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='response_user_crea', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_user_mod', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Creation Date and Time')),
                ('modified', models.DateField(editable=False, null=True, verbose_name='Modification Date and Time')),
                ('publish', models.BooleanField(default=True, help_text='Este campo activará el contenido en la pagina.', verbose_name='Publicar')),
                ('order', models.IntegerField(blank=True, default=0, help_text='Este campo será utilizado para definir el orden del contenido. ', verbose_name='Orden')),
                ('key', models.CharField(max_length=22, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='survey_user_crea', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_user_mod', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerInteger',
            fields=[
                ('answerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.AnswerBase')),
                ('body', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('surveys.answerbase',),
        ),
        migrations.CreateModel(
            name='AnswerRadio',
            fields=[
                ('answerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.AnswerBase')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('surveys.answerbase',),
        ),
        migrations.CreateModel(
            name='AnswerSelect',
            fields=[
                ('answerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.AnswerBase')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('surveys.answerbase',),
        ),
        migrations.CreateModel(
            name='AnswerSelectMultiple',
            fields=[
                ('answerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.AnswerBase')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('surveys.answerbase',),
        ),
        migrations.CreateModel(
            name='AnswerText',
            fields=[
                ('answerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.AnswerBase')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('surveys.answerbase',),
        ),
        migrations.CreateModel(
            name='CheckboxQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.Question')),
                ('max_checked', models.IntegerField(null=True)),
                ('min_checked', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('surveys.question',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.Question')),
            ],
            options={
                'abstract': False,
            },
            bases=('surveys.question',),
        ),
        migrations.CreateModel(
            name='NumericQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.Question')),
                ('min_value', models.FloatField(null=True)),
                ('max_value', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('surveys.question',),
        ),
        migrations.CreateModel(
            name='ParagraphQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.Question')),
                ('max_no_characters', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('surveys.question',),
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.Question')),
                ('max_no_characters', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('surveys.question',),
        ),
        migrations.AddField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='question_user_crea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_user_mod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.Survey'),
        ),
        migrations.AddField(
            model_name='answerbase',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='answerbase_user_crea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerbase',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answerbase_user_mod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerbase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Question'),
        ),
        migrations.AddField(
            model_name='answerbase',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Response'),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.MultipleChoiceQuestion'),
        ),
        migrations.AddField(
            model_name='checkboxchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.CheckboxQuestion'),
        ),
    ]
