# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='description',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='key',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='title',
        ),
        migrations.AddField(
            model_name='survey',
            name='l_q1',
            field=models.CharField(default='Please describe your current practice', max_length=128, verbose_name='label_q1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='q1',
            field=models.CharField(choices=[('a', 'Interventional Cardiologist/Fellow'), ('b', 'EP/Arrhythmia Specialist/Fellow'), ('c', 'General Cardiologist'), ('d', 'Internist'), ('e', 'Specialist in thrombosis (internal medicine, haematology, thrombosis)'), ('f', 'Cardiology resident'), ('g', 'Internal medicine resident')], default='a', max_length=1, verbose_name=''),
            preserve_default=False,
        ),
    ]
