# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 19:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0002_auto_20170318_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Creation Date and Time')),
                ('modified', models.DateField(editable=False, null=True, verbose_name='Modification Date and Time')),
                ('l_q1', models.CharField(max_length=128, verbose_name='label_q1')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='surveyquestion_user_crea', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveyquestion_user_mod', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='survey',
            name='l_q1',
        ),
    ]
