# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20170318_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerbase',
            name='response',
        ),
    ]
