# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 01:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0004_auto_20170319_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Creation Date and Time')),
                ('modified', models.DateField(editable=False, null=True, verbose_name='Modification Date and Time')),
                ('publish', models.BooleanField(default=True, help_text='Este campo activará el contenido en la pagina.', verbose_name='Publicar')),
                ('order', models.IntegerField(blank=True, default=0, help_text='Este campo será utilizado para definir el orden del contenido. ', verbose_name='Orden')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Creation Date and Time')),
                ('modified', models.DateField(editable=False, null=True, verbose_name='Modification Date and Time')),
                ('publish', models.BooleanField(default=True, help_text='Este campo activará el contenido en la pagina.', verbose_name='Publicar')),
                ('order', models.IntegerField(blank=True, default=0, help_text='Este campo será utilizado para definir el orden del contenido. ', verbose_name='Orden')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='response_user_crea', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_user_mod', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerCheckbox',
            fields=[
                ('answerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.AnswerBase')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('surveys.answerbase',),
        ),
        migrations.CreateModel(
            name='AnswerMultipleChoice',
            fields=[
                ('answerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.AnswerBase')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('surveys.answerbase',),
        ),
        migrations.CreateModel(
            name='AnswerNumeric',
            fields=[
                ('answerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.AnswerBase')),
                ('body', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('surveys.answerbase',),
        ),
        migrations.CreateModel(
            name='AnswerParagraph',
            fields=[
                ('answerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.AnswerBase')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('surveys.answerbase',),
        ),
        migrations.CreateModel(
            name='AnswerText',
            fields=[
                ('answerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surveys.AnswerBase')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('surveys.answerbase',),
        ),
        migrations.AddField(
            model_name='answerbase',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='answerbase_user_crea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerbase',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answerbase_user_mod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerbase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Question'),
        ),
        migrations.AddField(
            model_name='answerbase',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Response'),
        ),
    ]
