# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20170319_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='checkboxchoice',
            old_name='id_in_question',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='multiplechoice',
            old_name='id_in_question',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='id_in_survey',
        ),
    ]
