# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_auto_20170319_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkboxchoice',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='multiplechoice',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='answerbase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.Question'),
        ),
        migrations.AlterField(
            model_name='answerbase',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.Response'),
        ),
    ]
