# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-19 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_auto_20170319_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='help_text',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
