# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20170319_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.Survey'),
        ),
    ]
