# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_auto_20170320_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
