# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_auto_20170320_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerbase',
            options={'ordering': ['question__order']},
        ),
        migrations.AlterField(
            model_name='answerbase',
            name='order',
            field=models.IntegerField(blank=True, default=0, help_text='This field will be used to order the content', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='answerbase',
            name='publish',
            field=models.BooleanField(default=True, help_text='This field will activate the content in the site', verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(blank=True, default=0, help_text='This field will be used to order the content', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='question',
            name='publish',
            field=models.BooleanField(default=True, help_text='This field will activate the content in the site', verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='response',
            name='order',
            field=models.IntegerField(blank=True, default=0, help_text='This field will be used to order the content', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='response',
            name='publish',
            field=models.BooleanField(default=True, help_text='This field will activate the content in the site', verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='order',
            field=models.IntegerField(blank=True, default=0, help_text='This field will be used to order the content', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='publish',
            field=models.BooleanField(default=True, help_text='This field will activate the content in the site', verbose_name='Publish'),
        ),
    ]
