# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_auto_20170601_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='important_text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
